### ISSUE TITLE
trace: consider batching in ExportSpan

### ISSUE THREAD

**Issue by odeke-em** [honeycombio/opencensus-exporter#4]
It's great to see this exporter for OpenCensus from Honeycomb, congratulations!

I was just studying your exporter and noticed that in ExportSpan, per SpanData that's added it is converted immediately and then uploaded before ExportSpan returns.

ExportSpan is on the hot path and for example if we had 10K QPS all traces sampled say during a high latency spike, this would slow down the entire program since the number of SpanData being created will also be >=10K but also the network bandwidth from that upload of each span/event would spike too.

This is just a kind suggestion to perhaps perform some sort of batching. We talk about doing heavy work in a separate goroutine as per https://godoc.org/go.opencensus.io/trace#Exporter

and some exporters like Stackdriver use this bundler https://godoc.org/google.golang.org/api/support/bundler can allow you to set a "buffer time period" as well as a "batch max size".

Thank you.

**Comment by maplebed** [comment]
Hi and thanks for the comment! I completely understand and agree that ExportSpan must be fast to return in order to avoid blocking the main execution of the app. Though it's insufficiently clear from the documentation, the `Send()` function invoked in `ExportSpan` is actually asynchronous. It adds the event to a sending queue that then gets batched up (with batch size being based on either time or number of events, as you mention happens in bundler) and sent eventually. 

`ev.Send()` eventually calls `tx.Add()`, the function to add an event to the transmission queue. Its implementation is here: https://github.com/honeycombio/libhoney-go/blob/master/transmission.go#L72. We are using `facebookgo/muster` instead of bundler, and find it does an excellent job. 

libhoney does offer control over batch size and timing.  Would you suggest also exposing that configuration at the level of the Exporter?
